name: CI/CD

on:
 push:
   branches:
    - main
 pull_request:
   branches:
     - main

permissions:
 contents: read

jobs:
  vulnerability-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
         fetch-depth: 0

      - name: Installer unzip
        run: |
           sudo apt-get update
           sudo apt-get install -y unzip
      - name: Analyse Sonarqube
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        with:
          scannerVersion: 6.2.0.4584
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build project
    runs-on: ubuntu-24.04
    needs: vulnerability-scan

    steps:
      - name: Récupération du code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Installation des dépendances
        run: npm ci

      - name: Build du projet
        run: npm run build

      - name: Sauvegarde du dossier dist
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: vue-dist
          path: dist/

  trivy:
    name: SCA - Trivy
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Construction de l'image Docker
        run: |
          docker build -t vuejs-app:${{ github.sha }} .

      - name: Analyse de l'image avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: vuejs-app:${{ github.sha }}
          format: table
          exit-code: 0
          ignore-unfixed: true
          severity: CRITICAL,HIGH

  deploy:
    name: Déploiement
    runs-on: self-hosted
    needs: trivy

    steps:
      - name: Récupération du code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Construction de l'image Docker
        run: |
          docker build -t vuejs-app1:${{ github.sha }} .

      - name: Nettoyage de l'ancien conteneur
        run: |
          docker rm -f vuejs-app-prod || true

      - name: Déploiement
        run: |
          docker run -d \
            --name vuejs-app-prod \
            -p 8080:3000 \
            vuejs-app1:${{ github.sha }}

      - name: Vérification du deploiement
        run: |
          sleep 5
          curl -f http://172.20.21.20:8080

  zap:
    name: DAST - OWASP ZAP
    runs-on: ubuntu-24.04
    needs: deploy

    steps:
      - name: Scan OWASP ZAP
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'http://172.20.21.20:8080'
          cmd_options: '-a'
          fail_action: false
          artifact_name: 'zap-report'

      - name: Install wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf
      - name: Convert ZAP report into PDF
        run: wkhtmltopdf --enable-local-file-access report_html.html zap-report.pdf
      - name: Publish the report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: zap-report-pdf
          path: zap-report.pdf

  notify:
    runs-on: ubuntu-24.04
    needs: zap
    if: always()
    steps:
      - name: Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Download the ZAP report
        uses: actions/download-artifact@v4
        with:
          name: zap-report-pdf
          path: .

      - name: Send email with reports.
        uses: dawidd6/action-send-mail@67ce3558d613188179559c61d3565140cf389968
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Security Report"
          to: ${{ secrets.MAIL_TO }}
          from: KORVA Deployment Team <${{ secrets.MAIL_FROM }}>
          body: |
            Hello Team, here is Amalth! Haha!
          attachments: zap-report.pdf

